CREATE TABLE IF NOT EXISTS replyText (
    replyTextID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    postingUser INTEGER REFERENCES user(userID) ON DELETE SET NULL ON UPDATE CASCADE,
    creationTime INTEGER NOT NULL,
    text TEXT NOT NULL
);