DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user (
    userID INTEGER PRIMARY KEY AUTOINCREMENT,
    userName TEXT NOT NULL UNIQUE,
    passwordHash TEXT NOT NULL,
    isAdmin BOOLEAN NOT NULL DEFAULT 0,
    creationTime INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastVisit INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
);
